version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_VAPID_PUBLIC_KEY: ${VITE_VAPID_PUBLIC_KEY}
        container_name: securechat
        ports:
            - '${PORT:-8080}:80'
        restart: unless-stopped
        environment:
            - NODE_ENV=production
